services:
  postgres:
    image: postgres:16-alpine
    container_name: APP_NAME-postgres
    environment:
      POSTGRES_USER: APP_SNAKE
      POSTGRES_PASSWORD: password
      POSTGRES_DB: APP_SNAKE_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U APP_SNAKE"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
