// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Email confirmation tokens -------------------------------------------------
	CreateEmailConfirmationToken(ctx context.Context, arg CreateEmailConfirmationTokenParams) error
	// Password reset tokens -----------------------------------------------------
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error
	// Refresh tokens -----------------------------------------------------------
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetEmailConfirmationTokenByHash(ctx context.Context, tokenHash string) (EmailConfirmationToken, error)
	GetPasswordResetTokenByHash(ctx context.Context, tokenHash string) (PasswordResetToken, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	MarkEmailConfirmationTokenUsed(ctx context.Context, id uuid.UUID) error
	MarkPasswordResetTokenUsed(ctx context.Context, id uuid.UUID) error
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	SetUserEmailVerified(ctx context.Context, id uuid.UUID) (User, error)
	UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
