// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailConfirmationToken = `-- name: CreateEmailConfirmationToken :exec

INSERT INTO email_confirmation_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
`

type CreateEmailConfirmationTokenParams struct {
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

// Email confirmation tokens -------------------------------------------------
func (q *Queries) CreateEmailConfirmationToken(ctx context.Context, arg CreateEmailConfirmationTokenParams) error {
	_, err := q.db.Exec(ctx, createEmailConfirmationToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :exec

INSERT INTO password_reset_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
`

type CreatePasswordResetTokenParams struct {
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

// Password reset tokens -----------------------------------------------------
func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, createPasswordResetToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec

INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

// Refresh tokens -----------------------------------------------------------
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const getEmailConfirmationTokenByHash = `-- name: GetEmailConfirmationTokenByHash :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at FROM email_confirmation_tokens WHERE token_hash = $1
`

func (q *Queries) GetEmailConfirmationTokenByHash(ctx context.Context, tokenHash string) (EmailConfirmationToken, error) {
	row := q.db.QueryRow(ctx, getEmailConfirmationTokenByHash, tokenHash)
	var i EmailConfirmationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPasswordResetTokenByHash = `-- name: GetPasswordResetTokenByHash :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at FROM password_reset_tokens WHERE token_hash = $1
`

func (q *Queries) GetPasswordResetTokenByHash(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetTokenByHash, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, expires_at, revoked_at, created_at FROM refresh_tokens WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markEmailConfirmationTokenUsed = `-- name: MarkEmailConfirmationTokenUsed :exec
UPDATE email_confirmation_tokens SET used_at = now() WHERE id = $1
`

func (q *Queries) MarkEmailConfirmationTokenUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEmailConfirmationTokenUsed, id)
	return err
}

const markPasswordResetTokenUsed = `-- name: MarkPasswordResetTokenUsed :exec
UPDATE password_reset_tokens SET used_at = now() WHERE id = $1
`

func (q *Queries) MarkPasswordResetTokenUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPasswordResetTokenUsed, id)
	return err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}
